
services:
  travelready:
    image: ${CI_REGISTRY_IMAGE:-localhost:5050/root/travelready}:stable
    environment:
      - TR_ENV=PROD
      - CONFIG_PATH=/app/config.env
    volumes:
      - tr_data:/app/py/app/data/checked
    ports:
      - "127.0.0.1:5000:5000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD","python","-c","import urllib.request,sys; urllib.request.urlopen('http://localhost:5000/health'); sys.exit(0)"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 20s
volumes:
  tr_data: